### ISSUE TITLE
Signature policy identifier wrong

### ISSUE THREAD

**Issue by sander242** [open-eid/libdigidocpp#107]
The signature policy identifier for 
http://id.ee/public/bdoc-spec212-eng.pdf

should be:
urn:oid:1.3.6.1.4.1.10015.1000.3.2.3

instead we have:
urn:oid:1.3.6.1.4.1.10015.1000.3.2.1

https://github.com/open-eid/libdigidocpp/blob/master/src/SignatureXAdES_B.cpp#L66

**Comment by uudisaru** [comment]
Original change partly reverted because of the compatibility issues; BDOC policy 2.1.2 accepted when validating the signatures, but signing still uses original policy OID and document identifier.
