### ISSUE TITLE
include could not find load file: VersionInfo

### ISSUE THREAD

**Issue by colourful-land** [open-eid/libdigidocpp#130]
Compile failed for me on Ubuntu 17.04 with all dependencies installed.

libdigidocpp/build$ cmake ../

```
CMake Error at CMakeLists.txt:9 (include):
  include could not find load file:

    VersionInfo


CMake Error at CMakeLists.txt:12 (set_env):
  Unknown CMake command "set_env".


-- Configuring incomplete, errors occurred!
See also "libdigidocpp/build/CMakeFiles/CMakeOutput.log".
```
[CMakeOutput.log.gz](https://github.com/open-eid/libdigidocpp/files/1097510/CMakeOutput.log.gz)

**Comment by metsma** [comment]
do you have cmake folder content?
git clone --recursive libdigidocpp should checkout cmake submodule

**Comment by colourful-land** [comment]
Thank you. Pull request #133 thanks!
