### ISSUE TITLE
Depends on libxalan-c

### ISSUE THREAD

**Issue by pafcu** [open-eid/libdigidocpp#134]
The documentations fails to mention the dependency on `libxalan-c`, and cmake also fails to check that it is installed. Thus, if libxalan-c is not installed, compilation fails with

    libdigidocpp/src/Container.cpp:41:43: fatal error: xalanc/XPath/XPathEvaluator.hpp: No such file or directory
     #include <xalanc/XPath/XPathEvaluator.hpp>
                                           ^
    compilation terminated.

**Comment by metsma** [comment]
Xalan is not direct dependency. xml-security-c uses it for xpath.
https://github.com/open-eid/cmake/blob/master/modules/FindXmlSecurityC.cmake#L17
https://github.com/open-eid/libdigidocpp/blob/master/src/Container.cpp#L40

Which os it is?

**Comment by pafcu** [comment]
openSUSE Tumbleweed, using the xml-security-c provided by the official repositories

**Comment by metsma** [comment]
is it linked with xalan? or maybe suse packages do not have XSEC_NO_XALAN defined?

**Comment by pafcu** [comment]
It is linked against `libxalan-c`, so probably `XSEC_NO_XALAN` is _not_ defined (I assumed that the flag means that it is _not_ linked against xalan). However, this means that the header files _are_ included in `libdigidocpp/src/Container.cpp` due to the `#ifndef`. Perhaps the problem is that while `xml-security-c` _does_ depend on `libxalan-c`, it does _not_ depend on `libxalan-c-devel` which included the header files. The dependence on the header files comes directly from `libdigidocpp` so the dependency on the header files should be checked here. `FindXmlSecurityC.cmake` only checkes that the _library_ is installed, not the header files.

I may be totally wrong about how the flag works though.

**Comment by metsma** [comment]
strange, I assumed when you have xml-security-c-devel installed and it also depends then libxalan-c-devel? What happens when you install libxalan-c-devel?
Maybe add note then to docs when xml-security-c is linked with xalan then you need to have xalan devel packages

**Comment by pafcu** [comment]
Installing `xml-security-c-devel` fixes the problem, so adding a note to the readme might be a good idea, and because people won't read it anyway, maybe add a check in the .cmake-file too to check for the existence of the header files.

**Comment by metsma** [comment]
It actually has check for headers https://github.com/open-eid/cmake/blob/master/modules/FindXmlSecurityC.cmake#L14
We need figure somehow out If xml-security-c is linked against xalan and then hard require xalan devel packages

**Comment by pafcu** [comment]
OK, I'll take a close look at it and see if I can figure out what the problem is.

**Comment by pafcu** [comment]
Neither the openSUSE .rpm nor the Ubuntu or Debian .debs specify the xalan-c development files as a dependency, only xerces-c development files. Perhaps on Ubuntu the xalan-c development files are installed due to some other dependencies, which is why the problem has not been noticed before (I assume Debian/Ubuntu is the main Linux development platform)?

**Comment by metsma** [comment]
Ubuntu does not depend xalan https://packages.ubuntu.com/yakkety/libxml-security-c17v5
https://bugs.launchpad.net/ubuntu/+source/xml-security-c/+bug/1269434

**Comment by metsma** [comment]
Closing this issue for now
I don't see option to improve the situation in this project, needs to fixed upstream or least at Linux distro packaging
