### ISSUE TITLE
Enquire PDF signing feature progress

### ISSUE THREAD

**Issue by colourful-land** [open-eid/libdigidocpp#137]
I was super excited to see this on the pull request, and waited a while but didn't see it being merged. I also cloned the pdf branch from ~metsma/libdigidocpp and compiled, and using an unsigned pdf file in 'digidoc-tool sign' but the tool baild out.

Is it considered in working status on ~metsma/libdigidocpp pdf branch? Thanks!

**Comment by metsma** [comment]
Upstream has not decided if they support PDF natively or remote serivce.
I try to keep my PR up to date.
"and using an unsigned pdf file in 'digidoc-tool sign' but the tool baild out"
 can you explain more?
