### ISSUE TITLE
`sudo make install` issue

### ISSUE THREAD

**Issue by fisher** [open-eid/libdigidocpp#140]
After building and installing the software I've got an error:

```
0 (libdigidocpp:master) sofa% /usr/local/bin/digidoc-tool 
/usr/local/bin/digidoc-tool: error while loading shared libraries: libdigidocpp.so.1: cannot open shared object file: No such file or directory
127 (libdigidocpp:master) sofa% find ./ -name '*.so'
./src/libdigidocpp.so
0 (libdigidocpp:master) sofa% ldconfig -p |grep digido
1 (libdigidocpp:master) sofa%
```
I found that shared object has been installed in /usr/local/lib but ldconfig didn't know about it.
After running `ldconfig` the software starts as expected.

**Comment by metsma** [comment]
This is expected on linux https://stackoverflow.com/questions/4743233/is-usr-local-lib-searched-for-shared-libraries

**Comment by fisher** [comment]
So you're expecting your users to run `ldconfig` manually after making install? Not mentioning it on your README.md? Ook.

**Comment by metsma** [comment]
Users don't compile from sources. Developers do.
Developers have to know what is library and how to use them.
ldconfig is run every other linux distribution when installing software from packages.
