### ISSUE TITLE
Unable to validate signatures on a Lithuanian ADOC file on Linux

### ISSUE THREAD

**Issue by rimas-kudelis** [open-eid/libdigidocpp#143]
This comes from open-eid/qdigidoc#94. 

A signature that validates successfully on Windows and OS X, is displayed as invalid on Linux, with the following errors:
```
SignatureXAdES_B.cpp:529 Failed to validate signature: Reference URI="metadata/signableMetadata0.xml" failed to verify
Reference URI="metadata/signableMetadata0.xml" failed to verify
Reference URI="metadata/signableMetadata0.xml" failed to verify
```
I suspect this could be due to file system case-sensitivity, but that's just a guess.

**Comment by metsma** [comment]
I managed get the document do validate positive under ubuntu.
Created [xml-security-c](https://www.dropbox.com/s/zo45f24swetx0up/xmlsec.zip?dl=0) packages wich depend xalan-c and recompiled libdigidocpp

**Comment by rimas-kudelis** [comment]
Cool! Do you plan to put this package in your repo as well?

**Comment by rimas-kudelis** [comment]
Nope, but I thought I need an updated version of libdigidocpp as well? `apt` didn't see any updates there.

**Comment by metsma** [comment]
Can you compile and test it? I don't know when the next release will come of libdigidocpp

**Comment by rimas-kudelis** [comment]
If you have compiled a package already, I'd prefer to install it over compiling. :)

**Comment by metsma** [comment]
https://www.dropbox.com/s/ynq4xa9ahx6f1n2/libdigidocpp.zip?dl=0
It requires previous xml-security-c packages

**Comment by rimas-kudelis** [comment]
Yep, with these installed, one of the files validates successfully.

**Comment by metsma** [comment]
Latest release comes with repackaged xml-security-c
https://installer.id.ee/media/ubuntu/pool/main/x/xml-security-c/
