### ISSUE TITLE
Vajalik XSD >= 4.0

### ISSUE THREAD

**Issue by plaes** [open-eid/libdigidocpp#2]
`xsdcxx` väljakutsumisel kasutatakse `--std` valikut, mis on saadaval alates xsd-4.0.0 versioonist.

http://www.codesynthesis.com/pipermail/xsd-announcements/2014/000041.html

  * New option, --std, specifies the C++ standard that the generated code
    should conform to. Valid values are c++98 (default) and c++11.

**Comment by metsma** [comment]
xsd 4.0.0 on requirement
Support for ordered types. C++/Tree flattens nested compositors which
    sometimes can result in the loss of element ordering information that
    could be significant to the application. Ordered types address this
    problem. For more information, refer to Section 2.8.4, "Element Order"
    in the C++/Tree Mapping User Manual.

mis on vajalik Archive Timestamp allkirjade jaoks.

**Comment by plaes** [comment]
Jah, cmake võiks kontrollida seda...
