### ISSUE TITLE
Release tar.gz omits git submodules

### ISSUE THREAD

**Issue by smirnov** [open-eid/libdigidocpp#213]
It is impossible to use release tarballs to build a package, since submodule folders are empty. Is it possible to use --recursive checkout to form release tarballs?

**Comment by metsma** [comment]
Did you try https://github.com/open-eid/libdigidocpp/releases/download/v3.13.6/libdigidocpp-3.13.6.tar.gz ?

**Comment by smirnov** [comment]
Missed that one, sorry. Can be closed as notabug.
