### ISSUE TITLE
support for current podofo version 0.9.6

### ISSUE THREAD

**Issue by arekm** [open-eid/libdigidocpp#231]
Current podofo version (0.9.6) dropped pdfsiginc API:

"
    Remove obsolete PdfSigInc* API

    See tools/podofosign/podofosign.cpp for the replacement of it.
"

causing libdigidocpp to no longer build

https://github.com/svn2github/podofo/blob/master/tools/podofosign/podofosign.cpp.

Please consider supporting current podofo.

**Comment by glensc** [comment]
Don't link to branches!
- see https://news.ycombinator.com/item?id=8046710
  and https://help.github.com/articles/getting-permanent-links-to-files/
- hit `y`
- and perhaps https://github.com/josephfrazier/octopermalinker

**Comment by aidan-plenert-macdonald** [comment]
Related https://github.com/open-eid/libdigidocpp/pull/410. For example,

```
/home/aidan/foss/digidoc/libdigidocpp/src/PDF.cpp: In member function ‘PoDoFo::PdfAcroForm* digidoc::DSSPdfSigIncMemDocument::GetAcroForm()’:
/home/aidan/foss/digidoc/libdigidocpp/src/PDF.cpp:51:41: error: ‘GetExistedAcroForm’ was not declared in this scope
   51 |     PdfAcroForm* GetAcroForm() { return GetExistedAcroForm(nullptr); }
```

**Comment by klemensn** [comment]
The actual issue has been stale for years by now and most -if not all- sane operating systems are using OpenSSL>=1.1 by now.

Does it still makes sense to keep this old code around?
Or perhaps switch CMake to not use PoDoFo by default?

OpenBSD's port for example has always been disabling it:
https://github.com/openbsd/ports/blob/a015763b93d663421e15e7f233ae3ee7ed89b8c2/security/libdigidocpp/Makefile#L53-L55

**Comment by metsma** [comment]
By default it is now disabled https://github.com/open-eid/libdigidocpp/blob/master/CMakeLists.txt#L41
