### ISSUE TITLE
WinSigner missing ability to sign with software cert (from store)

### ISSUE THREAD

**Issue by triiberg** [open-eid/libdigidocpp#255]
WinSigner accepts 4 different ways to sign. The closest is "selectFirst". Please add 5th option to accept filter like thumbprint or some hash to select cert. And in that case WinSigner would read cert from cert store: software keys.

Usecase: today signing with KLASS3 cert uses PKCS12Signer that accepts cert as file (path, password). Storing files in file system is not the best practice. WinSigner is closest to provide this functionality, but accepts only hardware keys.

**Comment by tynisr** [comment]
Hi
After careful consideration we found that we will not add this feature request into developments roadmap which is financed by RIA. 
Nevertheless: libdigidocpp is open-source project and you can either yourself or through the help of previous committers develop missing function and send it as pull request. After code-review and tests we may include it to the release.
