### ISSUE TITLE
addDataFile throws "Document file test ääää.txt" does not exists." when filename or directory contains umlauts

### ISSUE THREAD

**Issue by jannikov** [open-eid/libdigidocpp#267]
I have libdigidocpp-3.13.8.1379 installed on windows 10

**Comment by metsma** [comment]
libdigidocpp API requires input to be UTF-8 encoding. Not ANSI local

**Comment by jannikov** [comment]
Yes, I have input in UTF8.
![image](https://user-images.githubusercontent.com/26857385/50768567-8a341780-1289-11e9-8eda-ac344f883446.png)
but anyway I got error
![image](https://user-images.githubusercontent.com/26857385/50768658-dbdca200-1289-11e9-8887-76726373f948.png)

**Comment by metsma** [comment]
57 line does not make any sense. Converting from utf-8 to utf-8?

**Comment by jannikov** [comment]
it only for example. To explain

**Comment by jannikov** [comment]
I changed the names. One filename is BDOC container and another one is file that should be signed
![image](https://user-images.githubusercontent.com/26857385/50769037-4b06c600-128b-11e9-90f2-e16485b76698.png)

**Comment by jannikov** [comment]
Maybe there is some trick with codepage? I already double checked, I have UTF 8

**Comment by jannikov** [comment]
And why you are doing filename conversions if you expect it in the utf8. \libdigidocpp\source\src\util\File.cpp Check fileExists -> encodeName -> convertUTF8

**Comment by metsma** [comment]
Seems like PINVOKE resolves parameters to local ANSI encoding.
This needs more investigating

**Comment by metsma** [comment]
Swig does not have c++ stream and C# stream mappings support right now

**Comment by jannikov** [comment]
SWIG even generates some wrapper for istream.

`public virtual void bbb(SWIGTYPE_p_std__istream arg0, string fileName, string mediaType) {
    digidocPINVOKE.Container_bbb(swigCPtr, SWIGTYPE_p_std__istream.getCPtr(arg0), fileName, mediaType);
    if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve();
  }`
`
[global::System.Runtime.InteropServices.DllImport("digidoc_csharp", EntryPoint="CSharp_digidoc_Container_bbb")]
  public static extern void Container_bbb(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, string jarg4);
`

**Comment by metsma** [comment]
> SWIG even generates some wrapper for istream.
> 
> `public virtual void bbb(SWIGTYPE_p_std__istream arg0, string fileName, string mediaType) { digidocPINVOKE.Container_bbb(swigCPtr, SWIGTYPE_p_std__istream.getCPtr(arg0), fileName, mediaType); if (digidocPINVOKE.SWIGPendingException.Pending) throw digidocPINVOKE.SWIGPendingException.Retrieve(); }`
> 
> global::System.Runtime.InteropServices.DllImport("digidoc_csharp", EntryPoint="CSharp_digidoc_Container_bbb")]
> public static extern void Container_bbb(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, string jarg4);
> `

This is not usable in C#
Here is list c++ std supported types
https://github.com/swig/swig/tree/master/Lib/csharp

**Comment by metsma** [comment]
Can you test https://ci.appveyor.com/project/open-eid/libdigidocpp/builds/21722020/job/xyc9cyf3879401vn/artifacts
if build completes

**Comment by jannikov** [comment]
Yes UTF8Marshaler works!
