### ISSUE TITLE
tsurl option to digidoc-tool

### ISSUE THREAD

**Issue by alvar-sk** [open-eid/libdigidocpp#286]
Currently there is not possible to change URL of the time-stamping service (ts.url) with digidoc-tool
https://github.com/open-eid/libdigidocpp/blob/7f8f58075201c87a72b4bcc592d4c13bbf138689/src/digidoc-tool.cpp#L278-L338

+

Another issue is that in manual default TSA url is "http://tsa.sk.ee/"
http://open-eid.github.io/libdigidocpp/manual.html#TS-settings

but actually it is configured to use "http://dd-at.ria.ee/tsa" by default
https://github.com/open-eid/libdigidocpp/blob/0b81460e344802ae7cdee82bed30d49076c10c81/CMakeLists.txt#L16

**Comment by Counter178** [comment]
Thank You for the information.
