### ISSUE TITLE
Better document ownership for C++ code

### ISSUE THREAD

**Issue by Hans-Giebenrath** [open-eid/libdigidocpp#322]
Hello,
I suggest improving the documentation on ownership of pointers handed back and forth in the Container class. Especially, I was bitten by the function `Container::addDataStream(std::istream* ptr, ...)`. Being used to using std::unique_ptr for [(idiomatic)](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#i11-never-transfer-ownership-by-a-raw-pointer-t-or-reference-t) ownership transfer, I used code as follows:

```
std::istringstream infile(in_filename);
auto container = std::unique_ptr<digidoc::Container>{digidoc::Container::create(out_filename)};
container->addDataFile(&stream, in_container_filename, "application/octet-stream");
container->save();
```

This blew up with a double free and it took me some time to realize (after reading documentation and the boost tests) that the API actually takes ownership.
`Container::create` returning a raw pointer also required me to look through documentation and tests whether there is some library internal memory management magic, as the [developer guidelines](https://open-eid.github.io/libdigidocpp/manual.html#containercreate) don't show a std::unique_ptr here, nor are they mentioning ownership in any case. Only a look into the boost tests gave me certainty that the caller becomes the owner of the objects.
The same applies to the other methods taking or returning a pointer. It seems like `Container::dataFiles` is not transferring ownership to the caller? `Container::prepareSignature` and `Container::sign` probably do? (I did not require those methods, yet, hence I have not looked up further documentation / tests / library internals to verify any of those hypotheses.) I have not looked at any other parts of the libdigidocpp API, so there may be potential for clarification, too.

I understand that due to API backwards compatibility it may not be feasible to migrate to a more idiomatic API. However, I suggest to at least improve the documentation (may it be as short as "takes ownership of [argument]" / "hands ownership of result to the caller"). This would have saved me an hour or two of gdb, searching documentation, reading tests, reading library internals.

I do not intend to criticize any of your work, I am merely suggesting an improvement.
Best Regards.

**Comment by Hans-Giebenrath** [comment]
Looking again at `ASiContainer::addDataFile(istream* is, ...)`, the `THROW`s in there require the caller to catch exceptions and release `is` itself, as otherwise it would leak (e.g. if there was already a signature). This is especially tricky and should be documented somewhere (or fixed, so that the caller does not need to handle this).
Additionally, if in the same function `push_back` throws `std::bad_alloc`, the newly allocated `DataFilePrivate` is leaked. But since hardening against out-of-memory conditions is a kind-of controversial topic in C++ (https://github.com/hsutter/babb) it may be the policy of your project to ignore `std::bad_alloc`, which is ok, but it may be nice to have a statement about this somewhere in the documentation.

**Comment by Hans-Giebenrath** [comment]
I am grateful that you addressed my concern. However, I think the chosen `const std::shared_ptr&` solution is a suboptimal solution (although it should be safer, now). If I find time I create a pull request with a unique_ptr.

(std::shared_ptr for a std::istream is on a philosophical level wrong in this scenario, since it means that there is potentially another owner of the std::istream. But it does not make sense to have multiple readers - only this container should read the file, and if it is read, close the istream. A second reader (a hypothetical owner other than the container) would only be able to consume the istream by itself, such that the container would either read a partial or empty file, which would lead to hard-to-debug bugs. Hence, a std::unique_ptr communicates the intend more clearly and prevents by-accident API abuse (or makes it a lot harder, at least).
On another level, taking a `const std::shared_ptr<T>&` (const lvalue reference) is (almost?) never a good argument type by itself, since the caller always needs to create a copy of the shared_ptr and cannot take advantage of move semantics - either take a `std::shared_ptr&&` (rvalue reference) or a `std::shared_ptr` (value), depending on whether you pass the `std::shared_ptr` further to another owner. Yes, in this case the performance hit is not noticeable since there is probably disk IO involved, but it would be nice if everyone wrote idiomatic C++ code so newcomers to C++ don't learn bad habits.
I emphasizedly suggest to use std::shared_ptr as a last resort only, as reasoning about the code now involves reasoning about the behavior of the potential other owners' behaviors)

Since this was a critical post, I want to repeat that I do not intend to criticize any of your work, I am merely suggesting an improvement.
Best regards.

**Comment by metsma** [comment]
I need verify thay all supported compilers support move semantics.
I can replace shared_ptr -> unique_ptr in PR.
Maybe we can use unique_ptr with Container::create/open and shared_ptr<Signature> objects

**Comment by Hans-Giebenrath** [comment]
I understand the concern with peculiarities of the supported compilers and I did not take this into account when reasoning about your changes - thank you for mentioning this constraint. If your time / budget allows it it would be nice if you checked how much you can migrate to `unique_ptr`s. But I can understand if you play safe and stick to the current solution for maximum compatibility (I have only Linux+gcc+clang experience and I have no idea how standards compatibility is outside of that realm).
Best regards.

**Comment by metsma** [comment]
Updated PR to unique_ptr

**Comment by metsma** [comment]
Closing: No feedback for while, reopen when needed
