### ISSUE TITLE
USE_TSL flag or other ways to disable TSL

### ISSUE THREAD

**Issue by Hans-Giebenrath** [open-eid/libdigidocpp#327]
Hello there,
I'd like to use the documented USE_TSL build parameter (https://open-eid.github.io/libdigidocpp/manual.html#initialization). I tried it with CMake (`cmake -DUSE_TSL=false [...]`) which did not work, and apparently `USE_TSL` is only mentioned ever in `RELEASE-NOTES.md` and other documentation files. I suspect that this is no longer a valid approach to disabling TSL?
My long term goal is to create containers without the library talking to the internet. Right now looking at https://open-eid.github.io/libdigidocpp/manual.html#TSL-init step 3 "The officially published hash value is downloaded", this looks like accessing the Internet is inevitable (if `USE_TSL` really is no longer around)?
Do I have any options here or do I need to fallback to creating the containers myself instead?

Thank you for your time.

**Comment by metsma** [comment]
I am sorry to notify this `USE_TSL ` flag is long gone and the documentation not updated.
I remove the flag from documentation.
There is possible download TSL files and store to cache and disable online check see `tsl.autoupdate` and `tsl.onlineDigest`
https://open-eid.github.io/libdigidocpp/manual.html#CA-settings.
One more option is to generate TSL files similar like here https://github.com/open-eid/test-TL and use custom trusted signing certificate
https://open-eid.github.io/libdigidocpp/classdigidoc_1_1Conf.html#ab9f072db46996436266d3f611414d7c5
