### ISSUE TITLE
Calling `PCKS11Signer::sign` twice throws, dedicated PIN Pad

### ISSUE THREAD

**Issue by Hans-Giebenrath** [open-eid/libdigidocpp#330]
I am not sure whether what I want to do is conceptually possible. Spelled out in code, this is what I want to do:

```
void fun(/* ... */) {
    // Slot/CardReader has dedicated PIN Pad, hence no subclass with pin method
    auto signer = digidoc::PKCS11Signer(opensc_0_20_0_driver);

    auto sign = [&](std::string const& from, std::string const& to) {
        std::unique_ptr<digidoc::Container> doc{digidoc::Container::open(from)};
        digidoc::Signature *signature = doc->sign(&signer);
        assert(signature);
        signature->validate();
        doc->save(to);
    };

    // succeeds
    sign(unsigned_asice_in1, signed_asice_out1);

    // throws "Failed to sign container", cause "Failed to sign digest"
    sign(unsigned_asice_in2, signed_asice_out2);
}
```

My goal is to sign multiple documents in one batch (as much as the user wants). For ease of use I hoped that it is possible to enter the PIN2 of the Estonian ID card only once when signing the first document and being cached thereafter. IIUC, this should be possible if one uses a card reader _without_ a dedicated PIN pad by subclassing the `PKCS11Signer` class and cache the user-entered PIN2 within the application. However, in my setting the card reader has a dedicated PIN pad (and hence caching the PIN within the application is impossible IIUC).

The toy code (not compiled, just a reduced version of my code which hopefully still illustrates the workflow) successfully signs (after entering the PIN2 on the dedicated PIN pad) and saves the first ASiC-E container, however the second `doc->sign` call (which reuses the `PKCS11Signer` object) fails with "Failed to sign digest" (without asking for a PIN2). Is this the intended result?

The debugger shows that in the second invocation of `doc->sign` [PKCS11Signer.cpp:327](https://github.com/open-eid/libdigidocpp/blob/master/src/crypto/PKCS11Signer.cpp#L327) returns `CKR_USER_ALREADY_LOGGED_IN`, but [PKCS11Signer.cpp:382](https://github.com/open-eid/libdigidocpp/blob/master/src/crypto/PKCS11Signer.cpp#L382) returns `0x101` (`CKR_USER_NOT_LOGGED_IN`), hence it throws.

I use the new OpenSC driver 0.20.0 (barely a week old, which natively supports the Estonian ID card, and it worked when using with the DigiDoc4 client) on Debian Buster.

The `CKR_..` return values seem contradictory, hence I am puzzled: Am I trying to achieve something impossible and I instead _must_ create a new signer for each container (forcing the user to enter the PIN2 for each container), or is this a bug in `libdigidocpp` or in `OpenSC 0.2.0`? Sadly I am missing any expertise whatsoever concerning PKCS#11 and the Estonian ID Card, hence I don't know where to start looking for a bug fix (if it is a bug at all).

**Comment by metsma** [comment]
This is not possible with PinPAD reader. Card only allows one sign operation per PIN authentication.
