### ISSUE TITLE
Feature request - create a simple web API to verify .asice signatures

### ISSUE THREAD

**Issue by marsrobertson** [open-eid/libdigidocpp#342]
https://www.id.ee/index.php?id=38861

> The easiest way is to open DigiDoc4 Client through which you can access the contents of the documents and verify signatures.

Both https://www.dokobit.com/ and https://www.eesti.ee/en/ require registration.

Not everyone can install software on their computer, think corporate machines with security policy.

**It would be super cool to have a public website that allows verifying signatures and public API.**  

_(can limit to 100 per day per IP address without API key)_

* `POST` the file
* Simple node.js server
* node.js [calling the process](https://stackoverflow.com/questions/5775088/how-to-execute-an-external-program-from-within-node-js)
* Some cpp magic `void digidoc::Signature::validate();`, [link to the doc](https://open-eid.github.io/libdigidocpp/manual.html#validate)
* Response to web request **VALID** or **INVALID** or **VALID WITH WARNINGS**

That's something 100% totally doable and I think it could facilitate adoption.

**Comment by Counter178** [comment]
Well, verifying signatures can be also done with SiVa https://github.com/open-eid/SiVa.

**Comment by marsrobertson** [comment]
@Counter178 I didn't have the slightest idea, that's why posted an issue. Thanks for letting us know!

@heyellieday https://github.com/heyellieday/eid-verify-docker

Me doing an onboarding demo for @EstoniaDAO: https://youtu.be/LjqNNFLzMWI
