### ISSUE TITLE
Verify .asice signature completely in the browser

### ISSUE THREAD

**Issue by marsrobertson** [open-eid/libdigidocpp#344]
Similar to #342 

You can totally do WASM C++ in the browser

- https://developer.mozilla.org/en-US/docs/WebAssembly/C_to_wasm
- https://webassembly.org/docs/c-and-c++/

**Comment by marsrobertson** [comment]
If not possible directly, then Windows 95 with Internet Explorer streaming pixels via animated GIF OCR via client-side TensorFlow reading from canvas 🐢🐢🐢all the down...

**Comment by kristelmerilain** [comment]
Thank you for the proposal.
Currently there are no plans to address this issue.
Verifying .asice signatures in browser can be done with https://joinup.ec.europa.eu/dss-webapp/validation or https://dss.nowina.lu/
There may be some slight differences in validation compared to the DigiDoc4 Client.
If you have any more questions then contact our support via help@ria.ee.
