### ISSUE TITLE
XALAN build error on release 3.14.3

### ISSUE THREAD

**Issue by Silur** [open-eid/libdigidocpp#363]
# Description

Building on `Linux 5.8.5-arch1-1 #1 SMP PREEMPT Thu, 27 Aug 2020 18:53:02 +0000 x86_64 GNU/Linux` results in lots of build errors around the `xalan-c` API:
```
.......
/home/silur/.cache/yay/libdigidocpp/src/src/Container.cpp:134:9: error: ‘XPathEvaluator’ has not been declared
  134 |         XPathEvaluator::initialize();
      |         ^~~~~~~~~~~~~~
/home/silur/.cache/yay/libdigidocpp/src/src/Container.cpp:135:9: error: ‘XalanTransformer’ has not been declared
  135 |         XalanTransformer::initialize();
      |         ^~~~~~~~~~~~~~~~
/home/silur/.cache/yay/libdigidocpp/src/src/Container.cpp: In function ‘void digidoc::terminate()’:
/home/silur/.cache/yay/libdigidocpp/src/src/Container.cpp:185:5: error: ‘XalanTransformer’ has not been declared
  185 |     XalanTransformer::terminate();
      |     ^~~~~~~~~~~~~~~~
/home/silur/.cache/yay/libdigidocpp/src/src/Container.cpp:186:5: error: ‘XPathEvaluator’ has not been declared
  186 |     XPathEvaluator::terminate();
      |     ^~~~~~~~~~~~~~
[ 64%] Building CXX object src/CMakeFiles/digidocpp.dir/SiVaContainer.cpp.o
```

# Steps to reproduce

```bash
cd /tmp
curl -L -O 'https://github.com/open-eid/libdigidocpp/releases/download/v3.14.3/libdigidocpp-3.14.3.tar.gz'
tar -xvzf libdigidocpp-3.14.3.tar.gz
cd libdigidocpp-3.14.3/
mkdir build
cd build
cmake ..
make
```
# System info

- Linux 5.8.5-arch1-1 #1 SMP PREEMPT Thu, 27 Aug 2020 18:53:02 +0000 x86_64 GNU/Linux
- cmake version 3.18.2
- xalan 1:1.12-1
- gcc 10.2.0

**Comment by metsma** [comment]
I'm not sure which distribution it is. Are development packages installed? Does xml-security-c depend of xalan-c?

**Comment by Silur** [comment]
somewhere along the chain it seems, `xml-securit-c` > `xerces-c` .....

But the first errors in the build process seems like a g++ incompatibility?

```
/home/silur/.cache/yay/libdigidocpp/src/src/Container.cpp:47:18: error: expected constructor, destructor, or type conversion before ‘(’ token
   47 | XALAN_USING_XALAN(XPathEvaluator)
      |                  ^
In file included from /usr/include/wctype.h:38,
                 from /usr/include/c++/10.2.0/cwctype:50,
                 from /usr/include/c++/10.2.0/bits/locale_facets.h:39,
                 from /usr/include/c++/10.2.0/bits/basic_ios.h:37,
                 from /usr/include/c++/10.2.0/ios:44,
                 from /usr/include/c++/10.2.0/istream:38,
                 from /usr/include/c++/10.2.0/sstream:38,
                 from /home/silur/.cache/yay/libdigidocpp/src/src/Container.cpp:52:
/usr/include/bits/wctype-wchar.h:155:8: error: ‘wctype_t’ does not name a type
  155 | extern wctype_t wctype (const char *__property) __THROW;
      |        ^~~~~~~~
/usr/include/bits/wctype-wchar.h:159:35: error: ‘wctype_t’ has not been declared
  159 | extern int iswctype (wint_t __wc, wctype_t __desc) __THROW;
      |                                   ^~~~~~~~
In file included from /usr/include/c++/10.2.0/cwctype:50,
                 from /usr/include/c++/10.2.0/bits/locale_facets.h:39,
                 from /usr/include/c++/10.2.0/bits/basic_ios.h:37,
                 from /usr/include/c++/10.2.0/ios:44,
                 from /usr/include/c++/10.2.0/istream:38,
                 from /usr/include/c++/10.2.0/sstream:38,
                 from /home/silur/.cache/yay/libdigidocpp/src/src/Container.cpp:52:
/usr/include/wctype.h:117:8: error: ‘wctype_t’ does not name a type
  117 | extern wctype_t wctype_l (const char *__property, locale_t __locale)
```

What are the official supported g++ versions?

**Comment by metsma** [comment]
I don't think we have tested xalan 1.12 version

**Comment by Silur** [comment]
xalan-c shipped a fix for this in 1.12-1, with this version the issue no longer persists, closing

**Comment by hsanjuan** [comment]
`1.12-1` is not an existing xalan-c release or anything. I built xalan-c from master and I get exactly the same thing.

**Comment by Silur** [comment]
@hsanjuan at least for arch linux [there is 1.12-1](https://www.archlinux.org/packages/community/x86_64/xalan-c/)

**Comment by hsanjuan** [comment]
So the first arch build for 1.12 that is. 1.12 is broken for me with the errors above. Arch did not incorporate any patch or anything on top of 1.12 that would fix the issue described above. Maybe you are running with something different, pretty sure not 1.12.

**Comment by metsma** [comment]
There seems to be tag in github https://github.com/apache/xalan-c/releases/tag/Xalan-C_1_12_0.
It is not compatible with xml-security-c because of public API changes.
Currently there is not possible use xalan-c 1.12.0 with xml-security-c and libdigidocpp

**Comment by musicinmybrain** [comment]
See also https://issues.apache.org/jira/browse/SANTUARIO-560 for xml-security-c.

In https://issues.apache.org/jira/browse/XALANC-780, a number of compatibility macros for ancient C++ compilers were removed. The following searches for the removed macros in a source directory:

```bash
grep -ErnI 'XALAN_(CPP_NAMESPACE_(BEGIN|END|USE)|USING_(STD|XALAN(_(CLASS|STRUCT))?)?|DECLARE_(CLASS|STRUCT)|STD_QUALIFIER|(NO_STD|HAS_CPP)_NAMESPACE)' /path/to/source
```

In both xml-security-c and libdigidocpp, it is the `XALAN_USING_XALAN` macro that causes the problem. The following fixes all occurrences in the source tree:

`find /path/to/libdigidocpp/ -type f -execdir sed -r -i 's/XALAN_USING_XALAN\(([^\(\)]+)\);*/using xalanc::\1;/g' '{}' '+'`

…which produces the patch:

```diff
diff --git a/src/Container.cpp b/src/Container.cpp
index 129322a..1a06f08 100644
--- a/src/Container.cpp
+++ b/src/Container.cpp
@@ -44,8 +44,8 @@ DIGIDOCPP_WARNING_PUSH
 DIGIDOCPP_WARNING_DISABLE_GCC("-Wunused-parameter")
 #include <xalanc/XalanTransformer/XalanTransformer.hpp>
 DIGIDOCPP_WARNING_POP
-XALAN_USING_XALAN(XPathEvaluator)
-XALAN_USING_XALAN(XalanTransformer)
+using xalanc::XPathEvaluator;
+using xalanc::XalanTransformer;
 #endif
 
 #define XSD_CXX11
```

I see there is an open PR, https://github.com/open-eid/libdigidocpp/pull/381, for other adjustments related to xalan-c 1.12. In Fedora, we found that the patch above, plus the corresponding patch in xml-security-c, was sufficient to make libdigidocpp compatible with the new xalan-c.
