### ISSUE TITLE
Creating signed .ascie container with digidoc-tool with Mobil-Id (command line)

### ISSUE THREAD

**Issue by dragonwebeu** [open-eid/libdigidocpp#364]
How do create signed container when using https://github.com/SK-EID/MID when I get back signature.value?

**Comment by metsma** [comment]
http://open-eid.github.io/libdigidocpp/manual.html#websigning
http://open-eid.github.io/libdigidocpp/manual.html#websign

**Comment by dragonwebeu** [comment]
This more like note for other, developer can fix me if I'm wrong.

You need wrapper for your programming language like Python and Ruby for your web app.

It can't be done by command line....
