### ISSUE TITLE
Linker error " Undefined symbols for architecture arm64"

### ISSUE THREAD

**Issue by edwardt** [open-eid/libdigidocpp#422]
export OPENSSL_ROOT_DIR="/usr/local/opt/openssl@1.1"
./build-library.sh osx

Undefined symbols for architecture arm64:
  "_ASN1_ANY_it", referenced from:
      QCStatement_seq_tt in X509Cert.cpp.o

**Comment by metsma** [comment]
Homebrew ships only with current arch binaries.
If you want build universal binarys, you need build openssl with prepare script.
Or export variable ARCHS="x86_64"
