### ISSUE TITLE
[Question] OCSP Verify cert logic. Why do we recalculate certID but not saved and reuse the one sent before?

### ISSUE THREAD

**Issue by edwardt** [open-eid/libdigidocpp#428]
Why do we recacularte the certID again but not reuse the one sent with OCSP request?

Recalculaltion of certID in method void OCSP::verifyResponse(const X509Cert &cert) const
https://github.com/open-eid/libdigidocpp/blob/master/src/crypto/OCSP.cpp#L328,L339

But not reuse the OCSP_CERTID *certId sent with OCSP request to OCSP responder in method OCSP::OCSP
https://github.com/open-eid/libdigidocpp/blob/master/src/crypto/OCSP.cpp#L102,L105

Also it is possible to use this library to very cert file -- certificate not originated from ssl context.?

**Comment by metsma** [comment]
> Why do we recacularte the certID again but not reuse the one sent with OCSP request?
> 
> Recalculaltion of certID in method void OCSP::verifyResponse(const X509Cert &cert) const
> https://github.com/open-eid/libdigidocpp/blob/master/src/crypto/OCSP.cpp#L328,L339

OCSP response can contain multiple cert_id-s. OCSP response does not specify cert_id digest method.
Thats why we loop each cert_id and look its digest method and try match the content.
Previously assumption was that cert_id is SHA1 and we can use default OpenSSL functions which does the job for us.

> But not reuse the OCSP_CERTID *certId sent with OCSP request to OCSP responder in method OCSP::OCSP
> https://github.com/open-eid/libdigidocpp/blob/master/src/crypto/OCSP.cpp#L102,L105
For creating OCSP request we request only one certificate status.

> Also it is possible to use this library to very cert file -- certificate not originated from ssl context.?
Currently it is not supported

**Comment by edwardt** [comment]
@metsma 
Why the library not reuse the cert_ID previously calculated when sending the OCSP request for a particular cert (the line OCSP_CERTID *certId = OCSP_cert_to_id(nullptr, cert.handle(), issuer.handle())) in 
 https://github.com/open-eid/libdigidocpp/blob/master/src/crypto/OCSP.cpp#L102,L105?

**Comment by metsma** [comment]
On validating signature later there is no ocps request sent and thus there is no ocspID
