### ISSUE TITLE
Adding support for other eID cards

### ISSUE THREAD

**Issue by eidins** [open-eid/libdigidocpp#440]
In order to support other eIDs to DigiDoc (eg. [Latvian](https://github.com/open-eid/DigiDoc4-Client/issues/995)), do any changes need to be made in this library? Will adding support to OpenSC (eg. [Latvian](https://github.com/OpenSC/OpenSC/pull/2428)) suffice to add support?

**Comment by metsma** [comment]
Most of them should work out of the box, eg. Latvian
