### ISSUE TITLE
Latvian ID Card needs to be set to CKM_SHA256_RSA_PKCS

### ISSUE THREAD

**Issue by eidins** [open-eid/libdigidocpp#442]
See https://github.com/OpenSC/OpenSC/pull/2428#issuecomment-962452011.

Latvian ID cards are getting incorrectly configured to CKM_RSA_PKCS when it should be CKM_SHA256_RSA_PKCS

https://github.com/open-eid/libdigidocpp/blob/a4f43532af711f791b6e53e191c000d2c1a445a8/src/crypto/PKCS11Signer.cpp#L373-L405

**Comment by metsma** [comment]
No it is expected to be CKM_RSA_PKCS and it works with propertary driver. OpenSC needs to be fixed
