### ISSUE TITLE
release containing 42a8cfd834c10bdd206fe784a13217df222b1c8e

### ISSUE THREAD

**Issue by flokli** [open-eid/libdigidocpp#474]
`qdigidoc4` and `digidoc-tool` are currently broken when linking with OpenSSL>1.1.1l.

It seems a fix for this already landed in master (42a8cfd834c10bdd206fe784a13217df222b1c8e).

Could you tag a release with this fix, so we don't need to pull patches downstream?

**Comment by klemensn** [comment]
This would be appreciated not just in NixOS but at least OpenBSD as well, for which I created new `qdigidoc4` and `libdigidocpp`.

It would be great if the next release would contain all other pending PRs (libdigidocpp, cmake, DigiDoc-Client).

**Comment by kristelmerilain** [comment]
New Libdigidocpp versions 3.14.9 and 3.14.10 are now available.
