### ISSUE TITLE
Nmake Error 

### ISSUE THREAD

**Issue by SananMS** [open-eid/libdigidocpp#479]
I am trying to use the command nmake; however, I get the following error:

```
Microsoft (R) Program Maintenance Utility Version 14.29.30145.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1064: MAKEFILE not found and no target specified
Stop.
```
What is the reason behind this?

**Comment by metsma** [comment]
Maybe cmake generate visual studio project ? or ninja?
Can you specify cmake generator -G"NMake Makefiles"

**Comment by SananMS** [comment]
How can I specify it? Furthermore, I get errors like these before using nmake:
`building xml-security-c:x64-windows-v141 failed with: BUILD_FAILED`
AND
`The following ICU libraries were not found: -- uc (required) -- data (required) -- Failed to find all ICU components (missing: ICU_INCLUDE_DIR ICU_LIBRARY _ICU_REQUIRED_LIBS_FOUND)`

**Comment by metsma** [comment]
I cannot say for sure. Can you post more logs

**Comment by kristelmerilain** [comment]
Closing due inactivity, reopen if needed.
