### ISSUE TITLE
prepare script failing to build xml-security-c

### ISSUE THREAD

**Issue by KristapsD** [open-eid/libdigidocpp#493]
I'm following the windows guide on the readme and trying to build this project.
System uses windows 11.
My system has VS 2017, 2019 and 2022 - all latest versions.
I've installed CMake (v 3.24) for windows, and Swig (v 4.0.2) as well.
Problem appears during the 3rd step of the building guide (i've only changed the toolset but it still fails with 141): running "powershell -ExecutionPolicy ByPass -File prepare_win_build_environment.ps1 -toolset 142",

I've added the console output log, and xml security buildtree log from the vcpkg folder as suggested by the console output. Console is also running in administrator mode.

[console output.txt](https://github.com/open-eid/libdigidocpp/files/9593613/console.output.txt)
[build-x64-windows-v142-rel-out.log](https://github.com/open-eid/libdigidocpp/files/9593614/build-x64-windows-v142-rel-out.log)

**Comment by metsma** [comment]
Seems like MFC or ATL component is required on Visual Studio install
fatal error RC1015: cannot open include file 'afxres.h'

**Comment by KristapsD** [comment]
Hi, thanks for your response.

I've double checked my vs 2019 installation and it has both MFC and ATL components installed, however only for the latest release of v142 build tools. Do i need a specific other version?

Also i've attached the buildtree log i got from the newest prep script attempt.

[build-x64-windows-v142-rel-out.log](https://github.com/open-eid/libdigidocpp/files/9596942/build-x64-windows-v142-rel-out.log)

**Comment by metsma** [comment]
Yes you need install them with same compiler set

**Comment by KristapsD** [comment]
i ended up switching to toolkit 141, and installing MFC and ATL for vs 2017, because with 2019 nothing was working. The preparing script ran fine after that without any errors.

After that now it's failing to run the configure step with cmake command. It says it fails to find PODOFO and xerces. but in the error logs it says it fails to open pthread.lib file. Am i still missing something from the installation/setup point?

Isn't the whole point in the prep script to build those dependencies? Anyways i have attached the cmake error, and output log files.
[CMakeError.log](https://github.com/open-eid/libdigidocpp/files/9598706/CMakeError.log)
[CMakeOutput.log](https://github.com/open-eid/libdigidocpp/files/9598708/CMakeOutput.log)

**Comment by metsma** [comment]
PoDoFo is optional dependency. Xerces is hard requirement
Seems like README.md is missing now how to reference vcpkg locations.
https://github.com/open-eid/libdigidocpp/blob/master/build.ps1#L70-L71
Here is github actions CI setup.
https://github.com/open-eid/libdigidocpp/blob/master/.github/workflows/build.yml#L130-L188
