### ISSUE TITLE
DigiDocCSharp multithreading

### ISSUE THREAD

**Issue by aleksei-oecd** [open-eid/libdigidocpp#507]
What is recommended way to use the lib in a multithreaded environment like a web application? I have tried using Singleton by calling digidoc.terminate(); on object creation and calling digidoc.terminate(); on disposal, but it seems it doesn't work.  It works for me if I use lib similar to this code:
```
void MyFunc()
{
  Conf.init(myConf);
  digidoc.initialize();
  try
  {
    .. prepare or sign logic here
  }
  finally
  {
      digidoc.terminate();
  }
}
```

but I'm afraid this code will be broken with multithreading. I could use locking, but maybe there is a better way ?

**Comment by metsma** [comment]
I suggest move digidoc.initialize() to beginning of service startup and digidoc.terminate() to end of service lifecycle.
As far keeping all container manipulation same thread you will be safe.
You can handle different containers in different threads.

**Comment by aleksei-oecd** [comment]
unfortunately doesn't work this way. if I call Conf.init(conf);  & digidoc.initialize() at the service start, then i get this error later when create container call is done when preparing signature when handling incoming request:
```
var container = Container.create(containerPath);
```

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at digidoc.digidocPINVOKE.Container_create(System.String)
--------------------------------
   at digidoc.Container.create(System.String)
```

If i Conf.init(conf);  & digidoc.initialize() are invoked in the same method before creating a Container everything works fine.

**Comment by aleksei-oecd** [comment]
A better example.  Logic similar to this works =>https://github.com/web-eid/web-eid-asp-dotnet-example/blob/b3ce8bff3b85d3e24b0f0f915a2aa006926960bb/src/WebEid.AspNetCore.Example/Signing/SigningService.cs#L34 But moving digidoc.initialize(); & digidoc.terminate(); to service startup and end accordingly produces error above when calling Container.create method

**Comment by metsma** [comment]
Strange, can you test latest https://github.com/open-eid/libdigidocpp/actions/runs/3359826798 msi artifacts.
There have been multiple fixes of memory leaks

**Comment by metsma** [comment]
Maybe service unloads the pinvoked dll?

**Comment by aleksei-oecd** [comment]
I will try the latest build, in the artifacts msi zip there are 3 files, which one should I should install ?

**Comment by metsma** [comment]
If you use C# then it does not matter. You should probably have latest VS runntime

**Comment by aleksei-oecd** [comment]
I ok my bad, it was because I did a custom setup removing documentation, development anx x86 during msi installation. If I install all all platform libs are in x64 folder. But still odd how documentation & development options influence the content of libs folder.

**Comment by metsma** [comment]
development option installs all lib and dbg symbols and also debug dll-s with "d" suffix.
https://github.com/open-eid/libdigidocpp/blob/master/libdigidocpp.wxs#L118-L142
if you remove the other options you should least have all required dll-s
https://github.com/open-eid/libdigidocpp/blob/master/libdigidocpp.wxs#L97-L117

**Comment by aleksei-oecd** [comment]
tried registering digidoc.initialize() at service start  in example application https://github.com/web-eid/web-eid-asp-dotnet-example. And there it worked fine, so something specific in my application then, will investigate further.

**Comment by aleksei-oecd** [comment]
It turned out it's not digidoc.initialize() that causes trouble but using a custom Config. If I don't use custom Conf.init everything works fine. Only if i init a custom before digidoc.initialize() something wrong with memory share.  Even calling Conf.instance().TSUrl() throws the same exception:

```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
```

**Comment by metsma** [comment]
Huh now this reminds me something. There was implemented Config.transfer() for not owning the C++ memory object when C# goes out of scope. Cannot remember of the correct usage, you need to play with it.
https://github.com/open-eid/libdigidocpp/blob/master/libdigidocpp.i#L240-L243

**Comment by aleksei-oecd** [comment]
yes, thank you, it seems it made a trick usage like the following works fine now:
```
Conf.init(new XmlConfV4(Path.Combine(AppContext.BaseDirectory, "digidocpp.conf.test")).transfer());
digidoc.digidoc.initialize();
```
