### ISSUE TITLE
PKCS12 .xml signature 

### ISSUE THREAD

**Issue by franfcunha** [open-eid/libdigidocpp#548]
Hi,

First of all, thanks for this work! 

I am trying to port some Python code to C++ to sign an .xml file with XADES-BES using a .p12 certificate. In order to familiarize with the library I am running the digidoc-tool in order to sign an xml and compare the resulting .xml with the one obtained with Python.

After creating the demo-container.asice I run `/usr/local/bin/digidoc-tool sign /home/franf/Desktop/demo-container.asice --pkcs12=/media/franf/dados/dev/CV-FE-587817798-CSE.p12 --pin=$MyPin`

which results into _Caught Exception: PKCS12Signer.cpp:64 code(General) Failed to parse PKCS12 certificate.
PKCS12 routines:0 code(General) error:23076071:PKCS12 routines:PKCS12_parse:mac verify failure_

In order to discard the possibility of having typed the wrong password, I've escaped special characters (e.g. exclamation marks) from $MyPin with no success.

Is there any available .cpp example on how to sign a .xml document using the ```PKCS12Signer``` class? I tried to adapt the available pkcs11sign.cpp code but the resulting .xml looks simply wrong. What I've tried:

```
static std::ostream &operator<<(std::ostream &s, const Exception &e)
{
    s << e.file() << ":" << e.line() << " code(" << e.code() << ") " << e.msg() << std::endl;
    for(const Exception &ex: e.causes())
        s << ex;
    return s;
}

int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    try
       {
           digidoc::initialize();
           std::unique_ptr<Container> doc(Container::createPtr("/tmp/test.asice"));

           doc->addDataFile("/media/franf/dados/dev/isolatedProjects/AssinaXmlXades/data/antesAssinatura.xml","text/plain");
           PKCS12Signer signer("/media/franf/dados/dev/CV-FE-587817798-CSE.p12","blabla");
           signer.setProfile("BES");
           doc->sign(&signer);
           doc->save("/media/franf/dados/dev/isolatedProjects/AssinaXmlXades/data/aposAssinaturaNovo.xml");
           digidoc::terminate();
       }
       catch(const Exception &e)
       {
           std::cout << e;
       }

    return 0;
}
```

**Comment by metsma** [comment]
This can be related due OpenSSL 3.0 changes
https://github.com/open-eid/libdigidocpp/wiki/Using-legacy-PKCS12-with-OpenSSL-3.0

**Comment by kristelmerilain** [comment]
Closing due inactivity, reopen if needed.
