### ISSUE TITLE
Signature validation Unable to verify signing certificate unable to get local issuer certificate

### ISSUE THREAD

**Issue by ajecka** [open-eid/libdigidocpp#556]
Hello. When validating a XAdES BES type signature, in some environments, we receive an exception:
"Signature validation Unable to verify signing certificate unable to get local issuer certificate".
looking at the source  code, the exception is most likely thrown here:
https://github.com/open-eid/libdigidocpp/blob/95c7c68d12eea89637deb695fdfe7abdbe109052/src/SignatureXAdES_B.cpp#L662

Only one of the two signature get this exception. 
The root certificate is installed in the trusted root providers.

I current have run out of ideas what the issue might be and I just need ideas what could be causes for the exception.

thanks for any help and please let me know if you need any additional details.

**Comment by metsma** [comment]
> The root certificate is installed in the trusted root providers.

Do you mean custom TSL-s are used?

**Comment by ajecka** [comment]
I mean the windows certificate store

**Comment by ajecka** [comment]
also, forgot to mention, only some signing certificates cause this issue. Other signatures validate correctly

**Comment by ajecka** [comment]
> libdigidocpp does not use windows certificate store https://open-eid.github.io/libdigidocpp/manual.html#TSL-overview

that good to know. thanks. 

> The root certificate is installed in the trusted root providers.

no, we do not use custom tsl.

**Comment by metsma** [comment]
I can suggest to create custom TSL list or modify code to trust certificates

**Comment by kristelmerilain** [comment]
Closing due inactivity, reopen if needed.
