### ISSUE TITLE
Verification of OCSP response which was produced more than 24 hours after signature timestamp

### ISSUE THREAD

**Issue by koliaq** [open-eid/libdigidocpp#6]
What is the reason for showing signature as invalid then it's OCSP response of signer certificate was produced at more than 24 hours after signature timestamp was created?

SignatureTS.cpp
161 else if(producedAtT - timeT > 24 * 60 * 60) // 24h
162    EXCEPTION_ADD(exception, "TimeStamp time and OCSP producedAt are over 24h");

**Comment by metsma** [comment]
It is inspired by this policy
https://github.com/open-eid/pdf-validator/blob/master/docs/policy.md
