### ISSUE TITLE
3.17.1 misses pull request #574

### ISSUE THREAD

**Issue by Germano0** [open-eid/libdigidocpp#600]
Hello, I am packaging for Fedora libdigidocpp 3.17.1, and I have noticed that the tar.gz misses the pull request https://github.com/open-eid/libdigidocpp/pull/574 by @ljavorsk that has been merged months before the 3.17.1 release

**Comment by metsma** [comment]
3.17.1 was branched from 3.17.0 and does not have this change

**Comment by plaes** [comment]
There still seems to be another issue regarding 3.17.1 tarball, commit a87d8d8fa33acb41da8a77699f447aa69801fa94 introduced some extra cmake files (notably `VersionInfo.cmake`) which are not included in tarball, resulting following issue:

```
$ tar -xzf ~/rpmbuild/SOURCES/libdigidocpp-3.17.1.tar.gz
$ cd libdigidocpp-3.17.1/
$ cmake .
-- The C compiler identification is GNU 14.1.1
-- The CXX compiler identification is GNU 14.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/lib64/ccache/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/lib64/ccache/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:8 (include):
  include could not find requested file:

    VersionInfo


CMake Error at CMakeLists.txt:11 (set_env):
  Unknown CMake command "set_env".
```

**Comment by metsma** [comment]
Is this github generated tar.gz or uploaded artifact?
```
tar tf libdigidocpp-3.17.1.tar.gz|grep VersionInfo
libdigidocpp-3.17.1/cmake/modules/VersionInfo.cmake
```

**Comment by plaes** [comment]
> Is this github generated tar.gz or uploaded artifact? Github ignored submodules. https://github.com/open-eid/libdigidocpp/releases/download/v3.17.1/libdigidocpp-3.17.1.tar.gz vs https://github.com/open-eid/libdigidocpp/archive/refs/tags/v3.17.1.tar.gz
> 
> ```
> tar tf libdigidocpp-3.17.1.tar.gz|grep VersionInfo
> libdigidocpp-3.17.1/cmake/modules/VersionInfo.cmake
> ```

Uff.. this is from the  tags page https://github.com/open-eid/libdigidocpp/tags :( 
![image](https://github.com/open-eid/libdigidocpp/assets/91895/db6b3aa5-633c-450e-a815-45ed1f30b46f)

**Comment by kristelmerilain** [comment]
Libdigidocpp newest release 4.0.0 contains the pull request https://github.com/open-eid/libdigidocpp/pull/574.
