### ISSUE TITLE
Custom TSL list question

### ISSUE THREAD

**Issue by Muzosh** [open-eid/libdigidocpp#602]
Hi,

at https://github.com/open-eid/libdigidocpp/wiki/Using-test-TSL-lists I see an alternative set of TSL master list, TSL list and TSL signing certificate.

Does RIA or SK have a common tool for creating these lists out of base x509 certificates? If so, is that tool public?

Thanks, Petr.

**Comment by metsma** [comment]
I manage XML files right now by hand and have self built tool to sign xml.
Maybe there is tool in https://github.com/esig/dss/ available (previously was https://github.com/esig/tlmanager)

**Comment by Muzosh** [comment]
Thanks

**Comment by Fethbita** [comment]
@metsma could you share your self built tool to sign the TSL xml?
