### ISSUE TITLE
(3.17.1 Release) Missing TARGET_OS_SIMULATOR Case in File::digidocppPath() on iOS Simulator

### ISSUE THREAD

**Issue by kevinmihkelson** [open-eid/libdigidocpp#630]
In release 3.17.1, there's an issue with the string File::digidocppPath() in src/util/File.cpp. The iOS Simulator-specific case is missing, causing it to fail on the simulator. This was added in a commit after the 3.17.1 release. I resolved the issue by manually adding:

`#elif defined(ANDROID) || TARGET_OS_SIMULATOR`

Can you please confirm if this fix will be included in the next release? Also, do you have an ETA for the new release, and will it include support for creating frameworks for iOS?

**Comment by metsma** [comment]
This is already in master branch
https://github.com/open-eid/libdigidocpp/blob/master/src/util/File.cpp#L282

**Comment by kevinmihkelson** [comment]
Yes, but when will a release be made with the fix?

**Comment by kristelmerilain** [comment]
We hope to release the new version next week.
