### ISSUE TITLE
Invalid package format under 4.0.0 release assets

### ISSUE THREAD

**Issue by janno-p** [open-eid/libdigidocpp#634]
It seems, that released package `libdigidocpp-4.0.0.tar.gz` is published without gzip-ing the package.

*Invalid content: GET /open-eid/libdigidocpp/releases/download/v4.0.0/libdigidocpp-4.0.0.tar.gz: org.sonatype.nexus.repository.InvalidContentException: Detected content type [application/x-tar], but expected [application/x-gzip, application/gzip, application/x-tgz, application/gzip-compressed, application/gzipped, application/x-gunzip, application/x-gzip-compressed, gzip/document]: open-eid/libdigidocpp/releases/download/v4.0.0/libdigidocpp-4.0.0.tar.gz*

Previous versions we're okay.

Would it be possible to fix it?

**Comment by metsma** [comment]
Fixed
