### ISSUE TITLE
Possible regression with v4 rewrite when verifying Undersign.js timestamps

### ISSUE THREAD

**Issue by moll** [open-eid/libdigidocpp#635]
Hey,

This could totally be [Undersign.js](https://github.com/moll/js-undersign)'s fault — perhaps by an unintentional reliance on some default option (XML c14n etc) — but worth covering here given widespread use of Undersign.js signatures — there are over 750k of those out there that I know of, most sent to Riigikogu and local governments. Riigikogu is how I just learned that v4.6 of Digidoc/libdigidocpp fails to accept Undersign.js's generated signatures due to a timestamp error.

Uve Lokk from Riigikogu is to thank for tracking this down to something that changed between v4.5.1 and v4.6.0. I now see a lot of code changes happened between those versions, so perhaps you can help track this down. I'll be code spelunging, too.

v4.6.0.4458 started failing to verify Undersign.js's created signatures with:
```
Failed to verify TS response.
error:17800067:time stamp routines::message imprint mismatch
```

I've attached an example signature ASiC-E from 2023. v4.5.1 accepted them fine, as presumably did earlier versions when Undersign.js was developed. I ran this file through Dokobit's validator, which last I checked used the EU DSS codebase, and that still considers it valid.

[Andri Möll (Smart-ID) on Hello with Microsec Timestamp.asice](https://github.com/user-attachments/files/17378471/Andri.Moll.Smart-ID.on.Hello.with.Microsec.Timestamp.zip)

Thanks in advance!

**Comment by metsma** [comment]
With EU DSS validation tool https://ec.europa.eu/digital-building-blocks/DSS/webapp-demo/validation I get
`AdES Validation Details:
The computed message-imprint does not match the value extracted from the time-stamp!`

**Comment by moll** [comment]
Hey, @metsma! Thanks! Right, DSS had an online validator exists. Turns out back in May I tracked _a_ DSS validation error down to the `<xades:SignatureTimeStamp>`'s c14n method and ensured its explicitly set in https://github.com/moll/js-undersign/commit/6b87bf5bec41c74e05a0df2b0c9d4b7359c73946. I didn't realize it would come back to haunt via Digidoc, too, and had forgotten about it.

So, as I understand it, Digidoc used to default the c14n method of `<ds:SignatureValue>` when verifying the timestamp to the one in `<SignedInfo>`. After https://github.com/open-eid/libdigidocpp/issues/576, it started defaulting to `http://www.w3.org/TR/2001/REC-xml-c14n-20010315` that the https://www.w3.org/TR/xmldsig-core1/#sec-CoreGeneration mentions. However, https://ec.europa.eu/digital-building-blocks/tracker/browse/DSS-2057 claims:

> Based on XMLDSIG (which also has been concluded during a plugtest members discussion), the default canonicalization algorithm is http://www.w3.org/2001/10/xml-exc-c14n# 

Was that a mistake and they've since fixed the defaulting to `http://www.w3.org/TR/2001/REC-xml-c14n-20010315` instead?

Thanks!

**Comment by metsma** [comment]
Yes they have corrected this later https://ec.europa.eu/digital-building-blocks/tracker/browse/DSS-2208
