### ISSUE TITLE
Cross-compiling Project for Multiple Targets on Linux (Ubuntu/Fedora)

### ISSUE THREAD

**Issue by tvildo** [open-eid/libdigidocpp#641]
Hi,

I am working on cross-compiling a project for the following targets: androidarm, androidarm64, and androidx86_64. I noticed that there is a prepare_osx_build_environment.sh script that helps with this process on macOS.

Is there a similar script or a set of instructions available for setting up a cross-compilation environment on Ubuntu or Fedora?

Thanks for your help!

Best regards,

**Comment by metsma** [comment]
Pleas look PR #620
