### ISSUE TITLE
Unable to download TSL list through a proxy

### ISSUE THREAD

**Issue by florian-ido** [open-eid/libdigidocpp#652]
Hi,

I am trying to download TSL through a HTTP proxy. I have set the parameters _proxy.host_ and _proxy.port_ properly (the proxy I am using does not require authentification, so I do not set _proxy.user_ and _proxy.pass_ parameters).

Iterating through the Connect::Connect method in Connect.cpp, I can see that at first, the connection to the proxy succeeds in this part of the code:

```
DEBUG("Connecting to Host: %s timeout: %i", hostname.c_str(), _timeout);
d = BIO_new_connect(hostname.c_str());
if (!d)
    THROW_NETWORKEXCEPTION("Failed to create connection with host: '%s'", hostname.c_str())

BIO_set_nbio(d, _timeout > 0);
auto start = chrono::high_resolution_clock::now();

if (timeout > 0 && BIO_do_connect_retry(d, timeout, -1) < 1)
    THROW_NETWORKEXCEPTION("Failed to create connection with host timeout: '%s'", hostname.c_str())
if (timeout == 0 && BIO_do_connect(d) < 1)
    THROW_NETWORKEXCEPTION("Failed to create connection with host: '%s'", hostname.c_str())
```

With _hostname_ variable being indeed equal to _proxy.host_:_proxy.port_.

But then, when we actually try to connect to host "ec.europa.eu" for downloading TSL, BIO_do_handshake(d) always returns -1 in the while loop in this part of the code:

```
BIO* sbio = BIO_new_ssl(ssl.get(), 1);
if (!sbio)
    THROW_NETWORKEXCEPTION("Failed to create ssl connection with host: '%s'", hostname.c_str())
if (SSL* ssl{}; BIO_get_ssl(sbio, &ssl) == 1 && ssl)
{
    SSL_set1_host(ssl, host.c_str());
    SSL_set_tlsext_host_name(ssl, host.c_str());
}
d = BIO_push(sbio, d);
while (BIO_do_handshake(d) != 1)
{
    if (_timeout == 0)
        THROW_NETWORKEXCEPTION("Failed to create ssl connection with host: '%s'", hostname.c_str())
    auto end = chrono::high_resolution_clock::now();
    if (chrono::duration_cast<chrono::seconds>(end - start).count() >= _timeout)
        THROW_NETWORKEXCEPTION("Failed to create ssl connection with host timeout: '%s'", hostname.c_str())
    this_thread::sleep_for(chrono::milliseconds(50));
}
```

I have already set the timeout to a high value to be sure that the problem is not coming from the timeout.

I know I can actually download TSL through my proxy as I have run another snippet of code using WinHttp library, and it works fine. I am using Windows 11.

Am I missing something here ? Any idea of what the problem could be ?

**Comment by metsma** [comment]
Does it get past of the proxy CONNECT request ?
https://github.com/open-eid/libdigidocpp/blob/e7bbc3030000136dd7d3a3ec821a8f47c1e814d4/src/crypto/Connect.cpp#L125-L135

**Comment by florian-ido** [comment]
In the example I was describing in my first message, it did not pass through this part of the code, because I had set the parameter _proxy.tunnelSSL_ to false. I am not very sure to understand exactly in which conditons the parameters _proxy.forceSSL_ and _proxy.tunnelSSL_ should be set to true or false.

Anyways, when I use the existing configuration for these two parameters (false for _proxy.forceSSL_ and true for _proxy.tunnelSSL_), it goes through this part of the code, but throws in the condition after the call to exec(): 

https://github.com/open-eid/libdigidocpp/blob/e7bbc3030000136dd7d3a3ec821a8f47c1e814d4/src/crypto/Connect.cpp#L132-L133

_r.isOK()_ returns true as HTTP status is 200, but _r.result_ here equals to the string "HTTP/1.0 200 OK", so it does pass the condition _r.result.find("established") == string::npos_.

**Comment by metsma** [comment]
Can you capture the traffic ?

**Comment by metsma** [comment]
Can you test this build https://github.com/open-eid/libdigidocpp/actions/runs/12408991033
install [msi_143_x64](https://github.com/open-eid/libdigidocpp/actions/runs/12408991033/artifacts/2342075347) package and copy C:\program files\libdigidocpp\digidocpp.dll to C:\program files\open-eid folder

**Comment by florian-ido** [comment]
It works well with your modifications, indeed it was simply a case sensitivity problem.

Thank you for your answers.

**Comment by kinomehhaanik** [comment]
> I am trying to download TSL through a HTTP proxy.

Can you reveal what proxy server software do you use?
Then we could test it in our environment as well.

We have not encountered such case sensitivity issue with Squid or any other proxy server we have tried.

**Comment by kinomehhaanik** [comment]
@fl-ido ?

> Can you reveal what proxy server software do you use? Then we could test it in our environment as well.

**Comment by fl-ido** [comment]
I was using free public proxies listed on some websites - not sure it is very relevant to test. But in my case if I remember well, it was returning a string with "Established" instead of "established", leading to the issue.
