### ISSUE TITLE
src/util/File.cpp:649: bad for loop ?

### ISSUE THREAD

**Issue by dcb314** [open-eid/libdigidocpp#7]
BUILD/libdigidocpp-3.12.1/src/util/File.cpp:649] -> [libdigidocpp-3.12.1/src/util/File.cpp:644]: (warning) Missing bounds check for extra iterator increment in loop.

Source code is

           data[2] = *(++i);
            data[3] = *(++i);

Suggest sanity check i is in range before incrementing it.

**Comment by Telgat** [comment]
Thanks for posting the issue.

    if(*i == '%' && isxdigit(*(i+1)) && isxdigit(*(i+2)))
    {
        data[2] = *(++i);
        data[3] = *(++i);
    ...
The calls to `isdigit()` here should make sure that the next two characters are hex digit characters and not the NULL string terminator, so we shouldn't end up going past the end of the input string, so the range check is sort of implicit here I guess.

In case I'm missing something here and you still think there could be an issue here please provide an example input string to demonstrate the problem.

**Comment by dcb314** [comment]
>I'm missing something here and you still think there could be an issue

I agree I haven't explained myself well enough. What happens if % is the last
char in the string ? Your code will call isxdigit on chars past end of string. 

I think your test for termination needs to be (i + 2) < length, not i < length.

**Comment by Telgat** [comment]
Indeed, I see the issue now. Thanks again for posting!
We'll fix it asap
